---
- name: APTキー用パッケージ
  apt:
    name: dirmngr

- name: APTキー追加
  shell: gpg --keyserver  keyring.debian.org --recv-keys  5C808C2B65558117;gpg --armor --export 5C808C2B65558117 | apt-key add -

- name: APT sources.list コピー
  copy: src=../files/sources.list dest=/etc/apt/sources.list

- name: APT アップデート
  apt: update_cache=yes


- name: APT アップグレード用パッケージ
  apt:
    name: aptitude

- name: APT アップグレード
  apt: update_cache=yes upgrade=yes
